### ISSUE TITLE
Flushes don't seem to be recognized. Also Jupiter card missing from Observatory option.

### ISSUE THREAD

**Issue by danhelias** [kleinfreund/balatrolator#9]
<img width="1537" alt="Screenshot 2024-12-08 at 8 19 44 PM" src="https://github.com/user-attachments/assets/e4ee0ab4-c8dc-4bd4-af59-60b4ea9dee68">

**Comment by kleinfreund** [comment]
(Please, when you report a bug, include the balatrolator.com URL so I can easily play around with your game state.)

For the state you're showing here, I redid the configuration here: https://balatrolator.com/?state=KwHwzCkIwgnCoowDQG41oExbcNVtUw1iicyQoAGWZAFmUaalSgDZlsnGW2rvmlbFG6sRI5BNb8RwxqjlNUADkmMOyEDNH9%2BTIA

The reason why your hand is not recognized as a flush is because you're playing a **stone** 6 of Spades. Cards with stone enhancement do not have a rank or suit; thus, they do not participate in forming flushes.
